[build]
  command = "npm run build"
  publish = "dist"
  base = "/"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  # ...existing configuration...

[build.environment]
  NODE_VERSION = "18.18.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimización de caché
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[functions]
directory = "netlify/functions"
