[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """default-src 'self' https://*.openstreetmap.org https://*.tile.openstreetmap.org https://*.openstreetmap.fr; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' https://www.googletagmanager.com; img-src 'self' data: https: https://*.tile.openstreetmap.org https://*.openstreetmap.fr; connect-src 'self' https: https://*.openstreetmap.org https://*.openstreetmap.fr;"""

# Optimización de caché
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[functions]
directory = "netlify/functions"
